---
name: etcd Server
version: "0.0.7"
slug: etcd
description: A distributed, reliable key-value store for the most critical data of a distributed system
url: https://github.com/alsotoes/hassio-infrastructure/tree/main/etcd
hassio_api: true
init: false
arch:
  - armv7
  - aarch64
panel_admin: false
ports:
  2379/tcp: 2379
  2380/tcp: 2380
options:
  INITIAL_CLUSTER_STATE: "existing"
  LOG_LEVEL: "info"
  NODE_NAME: "homeassistant"
schema:
  INITIAL_CLUSTER_STATE: list(existing|new)?
  LOG_LEVEL: list(debug|info|warn|error|panic|fatal)?
  NODE_NAME: "str"
startup: system
timeout: 300
map:
  - type: data
    read_only: false
  - type: backup
    read_only: false
