---
build_from:
  armv7: ghcr.io/hassio-addons/debian-base:7.1.0
  aarch64: ghcr.io/hassio-addons/debian-base:7.1.0
  amd64: ghcr.io/hassio-addons/debian-base:7.1.0
codenotary:
  base_image: notary@home-assistant.io
  signer: notary@home-assistant.io
