name: CUPS Print Server
slug: cups
description: "CUPS printing system with Avahi for AirPrint/IPP"
version: "1.4.1"
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
startup: services
host_network: true
init: false
map:
  - config:rw
  - share:rw
options:
  avahi_hostname: "cupsik"
  avahi_interface: "eth0"
  avahi_publish_workstation: false
  cups_service_name: "CUPS Print Server"
schema:
  avahi_hostname: str
  avahi_interface: str
  avahi_publish_workstation: bool
  cups_service_name: str
