---
name: etcd Server
version: "0.0.3"
slug: etcd
description: A distributed, reliable key-value store for the most critical data of a distributed system
url: https://github.com/alsotoes/ha-addons/tree/main/etcd-arm64
startup: services
init: false
arch:
  - armv7
init: false
homeassistant_api: false
ingress: true
ports:
  2379/tcp: 2379
  2380/tcp: 2380
ports_description:
  2379/tcp: etcd client requests 
  2380/tcp: etcd peer communication
panel_admin: false
backup_exclude:
  - "**/opt/bitnami/etcd/bin/**"
  - "**/opt/bitnami/etcd/conf.default/**"
  - "**/opt/bitnami/etcd/tmp/**"
options:
  ETCD_LOG_LEVEL: "info"
  ALLOW_NONE_AUTHENTICATION: "yes"
schema:
  ETCD_LOG_LEVEL: list(trace|debug|info|notice|warning|error|fatal)?
  ALLOW_NONE_AUTHENTICATION: "str"
